### ISSUE TITLE
Clone this repo

### ISSUE THREAD

**Issue by stephenjohnlimb** [ViliamVadocz/vscode-volpe-ls#1]
### Cloning
Do you mine if I clone this repo for my own language extension?
It will be for: [ek9](https://github.com/stephenjohnlimb/ek9 )

**Comment by ViliamVadocz** [comment]
Feel free to clone or fork this repo. Good luck with your language!

**Comment by stephenjohnlimb** [comment]
Thanks.
Steve

**Comment by stephenjohnlimb** [comment]
Thanks, I found your template very useful to get started with and have added snippets and syntax highlighting in for EK9.
